//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("BD_RESERVASModel", "FK_RecursoTipo_HoraTipo", "HoraTipo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ReservasUPN.BE.Modelos.HoraTipo), "RecursoTipo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ReservasUPN.BE.Modelos.RecursoTipo), true)]
[assembly: EdmRelationshipAttribute("BD_RESERVASModel", "FK_RecursoTipoUsuarioTipo_RecursoTipo", "RecursoTipo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ReservasUPN.BE.Modelos.RecursoTipo), "RecursoTipoHora", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ReservasUPN.BE.Modelos.RecursoTipoHora), true)]
[assembly: EdmRelationshipAttribute("BD_RESERVASModel", "FK_Usuario_TipoUsuario", "UsuarioTipo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ReservasUPN.BE.Modelos.UsuarioTipo), "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ReservasUPN.BE.Modelos.Usuario), true)]
[assembly: EdmRelationshipAttribute("BD_RESERVASModel", "FK_Recurso_RecursoTipo", "RecursoTipo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ReservasUPN.BE.Modelos.RecursoTipo), "Recurso", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ReservasUPN.BE.Modelos.Recurso), true)]

#endregion

namespace ReservasUPN.BE.Modelos
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BD_RESERVASEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BD_RESERVASEntities object using the connection string found in the 'BD_RESERVASEntities' section of the application configuration file.
        /// </summary>
        public BD_RESERVASEntities() : base("name=BD_RESERVASEntities", "BD_RESERVASEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BD_RESERVASEntities object.
        /// </summary>
        public BD_RESERVASEntities(string connectionString) : base(connectionString, "BD_RESERVASEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BD_RESERVASEntities object.
        /// </summary>
        public BD_RESERVASEntities(EntityConnection connection) : base(connection, "BD_RESERVASEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HoraTipo> HoraTipo
        {
            get
            {
                if ((_HoraTipo == null))
                {
                    _HoraTipo = base.CreateObjectSet<HoraTipo>("HoraTipo");
                }
                return _HoraTipo;
            }
        }
        private ObjectSet<HoraTipo> _HoraTipo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RecursoTipo> RecursoTipo
        {
            get
            {
                if ((_RecursoTipo == null))
                {
                    _RecursoTipo = base.CreateObjectSet<RecursoTipo>("RecursoTipo");
                }
                return _RecursoTipo;
            }
        }
        private ObjectSet<RecursoTipo> _RecursoTipo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RecursoTipoHora> RecursoTipoHora
        {
            get
            {
                if ((_RecursoTipoHora == null))
                {
                    _RecursoTipoHora = base.CreateObjectSet<RecursoTipoHora>("RecursoTipoHora");
                }
                return _RecursoTipoHora;
            }
        }
        private ObjectSet<RecursoTipoHora> _RecursoTipoHora;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuario> Usuario
        {
            get
            {
                if ((_Usuario == null))
                {
                    _Usuario = base.CreateObjectSet<Usuario>("Usuario");
                }
                return _Usuario;
            }
        }
        private ObjectSet<Usuario> _Usuario;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UsuarioTipo> UsuarioTipo
        {
            get
            {
                if ((_UsuarioTipo == null))
                {
                    _UsuarioTipo = base.CreateObjectSet<UsuarioTipo>("UsuarioTipo");
                }
                return _UsuarioTipo;
            }
        }
        private ObjectSet<UsuarioTipo> _UsuarioTipo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Recurso> Recurso
        {
            get
            {
                if ((_Recurso == null))
                {
                    _Recurso = base.CreateObjectSet<Recurso>("Recurso");
                }
                return _Recurso;
            }
        }
        private ObjectSet<Recurso> _Recurso;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Sancion> Sancion
        {
            get
            {
                if ((_Sancion == null))
                {
                    _Sancion = base.CreateObjectSet<Sancion>("Sancion");
                }
                return _Sancion;
            }
        }
        private ObjectSet<Sancion> _Sancion;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HoraTipo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHoraTipo(HoraTipo horaTipo)
        {
            base.AddObject("HoraTipo", horaTipo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RecursoTipo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRecursoTipo(RecursoTipo recursoTipo)
        {
            base.AddObject("RecursoTipo", recursoTipo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RecursoTipoHora EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRecursoTipoHora(RecursoTipoHora recursoTipoHora)
        {
            base.AddObject("RecursoTipoHora", recursoTipoHora);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuario(Usuario usuario)
        {
            base.AddObject("Usuario", usuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UsuarioTipo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuarioTipo(UsuarioTipo usuarioTipo)
        {
            base.AddObject("UsuarioTipo", usuarioTipo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Recurso EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRecurso(Recurso recurso)
        {
            base.AddObject("Recurso", recurso);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sancion EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSancion(Sancion sancion)
        {
            base.AddObject("Sancion", sancion);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_RESERVASModel", Name="HoraTipo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HoraTipo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HoraTipo object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static HoraTipo CreateHoraTipo(global::System.Int32 id)
        {
            HoraTipo horaTipo = new HoraTipo();
            horaTipo.id = id;
            return horaTipo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private Nullable<global::System.Boolean> _estado;
        partial void OnestadoChanging(Nullable<global::System.Boolean> value);
        partial void OnestadoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_RESERVASModel", "FK_RecursoTipo_HoraTipo", "RecursoTipo")]
        public EntityCollection<RecursoTipo> RecursoTipo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RecursoTipo>("BD_RESERVASModel.FK_RecursoTipo_HoraTipo", "RecursoTipo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RecursoTipo>("BD_RESERVASModel.FK_RecursoTipo_HoraTipo", "RecursoTipo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_RESERVASModel", Name="Recurso")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Recurso : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Recurso object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="codigo">Initial value of the codigo property.</param>
        /// <param name="descripcion">Initial value of the descripcion property.</param>
        /// <param name="tipoRecurso">Initial value of the tipoRecurso property.</param>
        /// <param name="estado">Initial value of the estado property.</param>
        public static Recurso CreateRecurso(global::System.Int32 id, global::System.String codigo, global::System.String descripcion, global::System.Int32 tipoRecurso, global::System.Boolean estado)
        {
            Recurso recurso = new Recurso();
            recurso.id = id;
            recurso.codigo = codigo;
            recurso.descripcion = descripcion;
            recurso.tipoRecurso = tipoRecurso;
            recurso.estado = estado;
            return recurso;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                OncodigoChanging(value);
                ReportPropertyChanging("codigo");
                _codigo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("codigo");
                OncodigoChanged();
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tipoRecurso
        {
            get
            {
                return _tipoRecurso;
            }
            set
            {
                OntipoRecursoChanging(value);
                ReportPropertyChanging("tipoRecurso");
                _tipoRecurso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tipoRecurso");
                OntipoRecursoChanged();
            }
        }
        private global::System.Int32 _tipoRecurso;
        partial void OntipoRecursoChanging(global::System.Int32 value);
        partial void OntipoRecursoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String caracteristicas
        {
            get
            {
                return _caracteristicas;
            }
            set
            {
                OncaracteristicasChanging(value);
                ReportPropertyChanging("caracteristicas");
                _caracteristicas = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("caracteristicas");
                OncaracteristicasChanged();
            }
        }
        private global::System.String _caracteristicas;
        partial void OncaracteristicasChanging(global::System.String value);
        partial void OncaracteristicasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Boolean _estado;
        partial void OnestadoChanging(global::System.Boolean value);
        partial void OnestadoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_RESERVASModel", "FK_Recurso_RecursoTipo", "RecursoTipo")]
        public RecursoTipo RecursoTipo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RecursoTipo>("BD_RESERVASModel.FK_Recurso_RecursoTipo", "RecursoTipo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RecursoTipo>("BD_RESERVASModel.FK_Recurso_RecursoTipo", "RecursoTipo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RecursoTipo> RecursoTipoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RecursoTipo>("BD_RESERVASModel.FK_Recurso_RecursoTipo", "RecursoTipo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RecursoTipo>("BD_RESERVASModel.FK_Recurso_RecursoTipo", "RecursoTipo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_RESERVASModel", Name="RecursoTipo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RecursoTipo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RecursoTipo object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="sede">Initial value of the sede property.</param>
        /// <param name="descripcion">Initial value of the descripcion property.</param>
        /// <param name="tipoHora">Initial value of the tipoHora property.</param>
        /// <param name="estado">Initial value of the estado property.</param>
        public static RecursoTipo CreateRecursoTipo(global::System.Int32 id, global::System.Int32 sede, global::System.String descripcion, global::System.Int32 tipoHora, global::System.Boolean estado)
        {
            RecursoTipo recursoTipo = new RecursoTipo();
            recursoTipo.id = id;
            recursoTipo.sede = sede;
            recursoTipo.descripcion = descripcion;
            recursoTipo.tipoHora = tipoHora;
            recursoTipo.estado = estado;
            return recursoTipo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sede
        {
            get
            {
                return _sede;
            }
            set
            {
                OnsedeChanging(value);
                ReportPropertyChanging("sede");
                _sede = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sede");
                OnsedeChanged();
            }
        }
        private global::System.Int32 _sede;
        partial void OnsedeChanging(global::System.Int32 value);
        partial void OnsedeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tipoHora
        {
            get
            {
                return _tipoHora;
            }
            set
            {
                OntipoHoraChanging(value);
                ReportPropertyChanging("tipoHora");
                _tipoHora = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tipoHora");
                OntipoHoraChanged();
            }
        }
        private global::System.Int32 _tipoHora;
        partial void OntipoHoraChanging(global::System.Int32 value);
        partial void OntipoHoraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Boolean _estado;
        partial void OnestadoChanging(global::System.Boolean value);
        partial void OnestadoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_RESERVASModel", "FK_RecursoTipo_HoraTipo", "HoraTipo")]
        public HoraTipo HoraTipo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HoraTipo>("BD_RESERVASModel.FK_RecursoTipo_HoraTipo", "HoraTipo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HoraTipo>("BD_RESERVASModel.FK_RecursoTipo_HoraTipo", "HoraTipo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<HoraTipo> HoraTipoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HoraTipo>("BD_RESERVASModel.FK_RecursoTipo_HoraTipo", "HoraTipo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<HoraTipo>("BD_RESERVASModel.FK_RecursoTipo_HoraTipo", "HoraTipo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_RESERVASModel", "FK_RecursoTipoUsuarioTipo_RecursoTipo", "RecursoTipoHora")]
        public EntityCollection<RecursoTipoHora> RecursoTipoHora
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RecursoTipoHora>("BD_RESERVASModel.FK_RecursoTipoUsuarioTipo_RecursoTipo", "RecursoTipoHora");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RecursoTipoHora>("BD_RESERVASModel.FK_RecursoTipoUsuarioTipo_RecursoTipo", "RecursoTipoHora", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_RESERVASModel", "FK_Recurso_RecursoTipo", "Recurso")]
        public EntityCollection<Recurso> Recurso
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Recurso>("BD_RESERVASModel.FK_Recurso_RecursoTipo", "Recurso");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Recurso>("BD_RESERVASModel.FK_Recurso_RecursoTipo", "Recurso", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_RESERVASModel", Name="RecursoTipoHora")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RecursoTipoHora : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RecursoTipoHora object.
        /// </summary>
        /// <param name="recursoTipo">Initial value of the recursoTipo property.</param>
        /// <param name="usuarioTipo">Initial value of the usuarioTipo property.</param>
        public static RecursoTipoHora CreateRecursoTipoHora(global::System.Int32 recursoTipo, global::System.Int32 usuarioTipo)
        {
            RecursoTipoHora recursoTipoHora = new RecursoTipoHora();
            recursoTipoHora.recursoTipo = recursoTipo;
            recursoTipoHora.usuarioTipo = usuarioTipo;
            return recursoTipoHora;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 recursoTipo
        {
            get
            {
                return _recursoTipo;
            }
            set
            {
                if (_recursoTipo != value)
                {
                    OnrecursoTipoChanging(value);
                    ReportPropertyChanging("recursoTipo");
                    _recursoTipo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("recursoTipo");
                    OnrecursoTipoChanged();
                }
            }
        }
        private global::System.Int32 _recursoTipo;
        partial void OnrecursoTipoChanging(global::System.Int32 value);
        partial void OnrecursoTipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 usuarioTipo
        {
            get
            {
                return _usuarioTipo;
            }
            set
            {
                if (_usuarioTipo != value)
                {
                    OnusuarioTipoChanging(value);
                    ReportPropertyChanging("usuarioTipo");
                    _usuarioTipo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("usuarioTipo");
                    OnusuarioTipoChanged();
                }
            }
        }
        private global::System.Int32 _usuarioTipo;
        partial void OnusuarioTipoChanging(global::System.Int32 value);
        partial void OnusuarioTipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> nroHoras
        {
            get
            {
                return _nroHoras;
            }
            set
            {
                OnnroHorasChanging(value);
                ReportPropertyChanging("nroHoras");
                _nroHoras = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nroHoras");
                OnnroHorasChanged();
            }
        }
        private Nullable<global::System.Int32> _nroHoras;
        partial void OnnroHorasChanging(Nullable<global::System.Int32> value);
        partial void OnnroHorasChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_RESERVASModel", "FK_RecursoTipoUsuarioTipo_RecursoTipo", "RecursoTipo")]
        public RecursoTipo RecursoTipo1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RecursoTipo>("BD_RESERVASModel.FK_RecursoTipoUsuarioTipo_RecursoTipo", "RecursoTipo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RecursoTipo>("BD_RESERVASModel.FK_RecursoTipoUsuarioTipo_RecursoTipo", "RecursoTipo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RecursoTipo> RecursoTipo1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RecursoTipo>("BD_RESERVASModel.FK_RecursoTipoUsuarioTipo_RecursoTipo", "RecursoTipo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RecursoTipo>("BD_RESERVASModel.FK_RecursoTipoUsuarioTipo_RecursoTipo", "RecursoTipo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_RESERVASModel", Name="Sancion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sancion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Sancion object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="fechainicio">Initial value of the fechainicio property.</param>
        /// <param name="estado">Initial value of the estado property.</param>
        public static Sancion CreateSancion(global::System.Int32 id, global::System.DateTime fechainicio, global::System.Boolean estado)
        {
            Sancion sancion = new Sancion();
            sancion.id = id;
            sancion.fechainicio = fechainicio;
            sancion.estado = estado;
            return sancion;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> usuario
        {
            get
            {
                return _usuario;
            }
            set
            {
                OnusuarioChanging(value);
                ReportPropertyChanging("usuario");
                _usuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("usuario");
                OnusuarioChanged();
            }
        }
        private Nullable<global::System.Int32> _usuario;
        partial void OnusuarioChanging(Nullable<global::System.Int32> value);
        partial void OnusuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String motivo
        {
            get
            {
                return _motivo;
            }
            set
            {
                OnmotivoChanging(value);
                ReportPropertyChanging("motivo");
                _motivo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("motivo");
                OnmotivoChanged();
            }
        }
        private global::System.String _motivo;
        partial void OnmotivoChanging(global::System.String value);
        partial void OnmotivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fechainicio
        {
            get
            {
                return _fechainicio;
            }
            set
            {
                OnfechainicioChanging(value);
                ReportPropertyChanging("fechainicio");
                _fechainicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechainicio");
                OnfechainicioChanged();
            }
        }
        private global::System.DateTime _fechainicio;
        partial void OnfechainicioChanging(global::System.DateTime value);
        partial void OnfechainicioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fechafin
        {
            get
            {
                return _fechafin;
            }
            set
            {
                OnfechafinChanging(value);
                ReportPropertyChanging("fechafin");
                _fechafin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechafin");
                OnfechafinChanged();
            }
        }
        private Nullable<global::System.DateTime> _fechafin;
        partial void OnfechafinChanging(Nullable<global::System.DateTime> value);
        partial void OnfechafinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Boolean _estado;
        partial void OnestadoChanging(global::System.Boolean value);
        partial void OnestadoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_RESERVASModel", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="tipoUsuario">Initial value of the tipoUsuario property.</param>
        /// <param name="codigo">Initial value of the codigo property.</param>
        /// <param name="estado">Initial value of the estado property.</param>
        public static Usuario CreateUsuario(global::System.Int32 id, global::System.Int32 tipoUsuario, global::System.String codigo, global::System.Boolean estado)
        {
            Usuario usuario = new Usuario();
            usuario.id = id;
            usuario.tipoUsuario = tipoUsuario;
            usuario.codigo = codigo;
            usuario.estado = estado;
            return usuario;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tipoUsuario
        {
            get
            {
                return _tipoUsuario;
            }
            set
            {
                OntipoUsuarioChanging(value);
                ReportPropertyChanging("tipoUsuario");
                _tipoUsuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tipoUsuario");
                OntipoUsuarioChanged();
            }
        }
        private global::System.Int32 _tipoUsuario;
        partial void OntipoUsuarioChanging(global::System.Int32 value);
        partial void OntipoUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                OncodigoChanging(value);
                ReportPropertyChanging("codigo");
                _codigo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("codigo");
                OncodigoChanged();
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Boolean _estado;
        partial void OnestadoChanging(global::System.Boolean value);
        partial void OnestadoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_RESERVASModel", "FK_Usuario_TipoUsuario", "UsuarioTipo")]
        public UsuarioTipo UsuarioTipo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsuarioTipo>("BD_RESERVASModel.FK_Usuario_TipoUsuario", "UsuarioTipo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsuarioTipo>("BD_RESERVASModel.FK_Usuario_TipoUsuario", "UsuarioTipo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UsuarioTipo> UsuarioTipoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsuarioTipo>("BD_RESERVASModel.FK_Usuario_TipoUsuario", "UsuarioTipo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UsuarioTipo>("BD_RESERVASModel.FK_Usuario_TipoUsuario", "UsuarioTipo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_RESERVASModel", Name="UsuarioTipo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UsuarioTipo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UsuarioTipo object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="nombre">Initial value of the nombre property.</param>
        /// <param name="estado">Initial value of the estado property.</param>
        public static UsuarioTipo CreateUsuarioTipo(global::System.Int32 id, global::System.String nombre, global::System.Boolean estado)
        {
            UsuarioTipo usuarioTipo = new UsuarioTipo();
            usuarioTipo.id = id;
            usuarioTipo.nombre = nombre;
            usuarioTipo.estado = estado;
            return usuarioTipo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Boolean _estado;
        partial void OnestadoChanging(global::System.Boolean value);
        partial void OnestadoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_RESERVASModel", "FK_Usuario_TipoUsuario", "Usuario")]
        public EntityCollection<Usuario> Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Usuario>("BD_RESERVASModel.FK_Usuario_TipoUsuario", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Usuario>("BD_RESERVASModel.FK_Usuario_TipoUsuario", "Usuario", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
