//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("BD_RESERVASModel", "FK_Usuario_TipoUsuario", "UsuarioTipo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ReservasUPN.BE.Modelos.UsuarioTipo), "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ReservasUPN.BE.Modelos.Usuario), true)]
[assembly: EdmRelationshipAttribute("BD_RESERVASModel", "FK_Recurso_RecursoTipo", "RecursoTipo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ReservasUPN.BE.Modelos.RecursoTipo), "Recurso", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ReservasUPN.BE.Modelos.Recurso), true)]
[assembly: EdmRelationshipAttribute("BD_RESERVASModel", "FK_RecursoTipoUsuarioTipo_RecursoTipo", "RecursoTipo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ReservasUPN.BE.Modelos.RecursoTipo), "RecursoTipoHora", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ReservasUPN.BE.Modelos.RecursoTipoHora), true)]
[assembly: EdmRelationshipAttribute("BD_RESERVASModel", "FK_RecursoTipo_HoraTipo", "HoraTipo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ReservasUPN.BE.Modelos.HoraTipo), "RecursoTipo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ReservasUPN.BE.Modelos.RecursoTipo), true)]

#endregion

namespace ReservasUPN.BE.Modelos
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class BD_RESERVASEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto BD_RESERVASEntities usando la cadena de conexión encontrada en la sección 'BD_RESERVASEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public BD_RESERVASEntities() : base("name=BD_RESERVASEntities", "BD_RESERVASEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BD_RESERVASEntities.
        /// </summary>
        public BD_RESERVASEntities(string connectionString) : base(connectionString, "BD_RESERVASEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BD_RESERVASEntities.
        /// </summary>
        public BD_RESERVASEntities(EntityConnection connection) : base(connection, "BD_RESERVASEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<UsuarioTipo> UsuarioTipo
        {
            get
            {
                if ((_UsuarioTipo == null))
                {
                    _UsuarioTipo = base.CreateObjectSet<UsuarioTipo>("UsuarioTipo");
                }
                return _UsuarioTipo;
            }
        }
        private ObjectSet<UsuarioTipo> _UsuarioTipo;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Usuario> Usuario
        {
            get
            {
                if ((_Usuario == null))
                {
                    _Usuario = base.CreateObjectSet<Usuario>("Usuario");
                }
                return _Usuario;
            }
        }
        private ObjectSet<Usuario> _Usuario;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<RecursoTipo> RecursoTipo
        {
            get
            {
                if ((_RecursoTipo == null))
                {
                    _RecursoTipo = base.CreateObjectSet<RecursoTipo>("RecursoTipo");
                }
                return _RecursoTipo;
            }
        }
        private ObjectSet<RecursoTipo> _RecursoTipo;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Recurso> Recurso
        {
            get
            {
                if ((_Recurso == null))
                {
                    _Recurso = base.CreateObjectSet<Recurso>("Recurso");
                }
                return _Recurso;
            }
        }
        private ObjectSet<Recurso> _Recurso;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<RecursoTipoHora> RecursoTipoHora
        {
            get
            {
                if ((_RecursoTipoHora == null))
                {
                    _RecursoTipoHora = base.CreateObjectSet<RecursoTipoHora>("RecursoTipoHora");
                }
                return _RecursoTipoHora;
            }
        }
        private ObjectSet<RecursoTipoHora> _RecursoTipoHora;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<HoraTipo> HoraTipo
        {
            get
            {
                if ((_HoraTipo == null))
                {
                    _HoraTipo = base.CreateObjectSet<HoraTipo>("HoraTipo");
                }
                return _HoraTipo;
            }
        }
        private ObjectSet<HoraTipo> _HoraTipo;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet UsuarioTipo. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUsuarioTipo(UsuarioTipo usuarioTipo)
        {
            base.AddObject("UsuarioTipo", usuarioTipo);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Usuario. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUsuario(Usuario usuario)
        {
            base.AddObject("Usuario", usuario);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet RecursoTipo. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToRecursoTipo(RecursoTipo recursoTipo)
        {
            base.AddObject("RecursoTipo", recursoTipo);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Recurso. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToRecurso(Recurso recurso)
        {
            base.AddObject("Recurso", recurso);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet RecursoTipoHora. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToRecursoTipoHora(RecursoTipoHora recursoTipoHora)
        {
            base.AddObject("RecursoTipoHora", recursoTipoHora);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet HoraTipo. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToHoraTipo(HoraTipo horaTipo)
        {
            base.AddObject("HoraTipo", horaTipo);
        }

        #endregion

        #region Importaciones de funciones
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="p_CODIGO">No hay documentación de metadatos disponible.</param>
        public ObjectResult<PA_SELECT_USUARIOS_X_CODIGO_Result> PA_SELECT_USUARIOS_X_CODIGO(global::System.String p_CODIGO)
        {
            ObjectParameter p_CODIGOParameter;
            if (p_CODIGO != null)
            {
                p_CODIGOParameter = new ObjectParameter("P_CODIGO", p_CODIGO);
            }
            else
            {
                p_CODIGOParameter = new ObjectParameter("P_CODIGO", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<PA_SELECT_USUARIOS_X_CODIGO_Result>("PA_SELECT_USUARIOS_X_CODIGO", p_CODIGOParameter);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_RESERVASModel", Name="HoraTipo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HoraTipo : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto HoraTipo.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        public static HoraTipo CreateHoraTipo(global::System.Int32 id)
        {
            HoraTipo horaTipo = new HoraTipo();
            horaTipo.id = id;
            return horaTipo;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private Nullable<global::System.Boolean> _estado;
        partial void OnestadoChanging(Nullable<global::System.Boolean> value);
        partial void OnestadoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_RESERVASModel", "FK_RecursoTipo_HoraTipo", "RecursoTipo")]
        public EntityCollection<RecursoTipo> RecursoTipo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RecursoTipo>("BD_RESERVASModel.FK_RecursoTipo_HoraTipo", "RecursoTipo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RecursoTipo>("BD_RESERVASModel.FK_RecursoTipo_HoraTipo", "RecursoTipo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_RESERVASModel", Name="Recurso")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Recurso : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Recurso.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="codigo">Valor inicial de la propiedad codigo.</param>
        /// <param name="descripcion">Valor inicial de la propiedad descripcion.</param>
        /// <param name="tipoRecurso">Valor inicial de la propiedad tipoRecurso.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        public static Recurso CreateRecurso(global::System.Int32 id, global::System.String codigo, global::System.String descripcion, global::System.Int32 tipoRecurso, global::System.Boolean estado)
        {
            Recurso recurso = new Recurso();
            recurso.id = id;
            recurso.codigo = codigo;
            recurso.descripcion = descripcion;
            recurso.tipoRecurso = tipoRecurso;
            recurso.estado = estado;
            return recurso;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                OncodigoChanging(value);
                ReportPropertyChanging("codigo");
                _codigo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("codigo");
                OncodigoChanged();
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tipoRecurso
        {
            get
            {
                return _tipoRecurso;
            }
            set
            {
                OntipoRecursoChanging(value);
                ReportPropertyChanging("tipoRecurso");
                _tipoRecurso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tipoRecurso");
                OntipoRecursoChanged();
            }
        }
        private global::System.Int32 _tipoRecurso;
        partial void OntipoRecursoChanging(global::System.Int32 value);
        partial void OntipoRecursoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String caracteristicas
        {
            get
            {
                return _caracteristicas;
            }
            set
            {
                OncaracteristicasChanging(value);
                ReportPropertyChanging("caracteristicas");
                _caracteristicas = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("caracteristicas");
                OncaracteristicasChanged();
            }
        }
        private global::System.String _caracteristicas;
        partial void OncaracteristicasChanging(global::System.String value);
        partial void OncaracteristicasChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Boolean _estado;
        partial void OnestadoChanging(global::System.Boolean value);
        partial void OnestadoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_RESERVASModel", "FK_Recurso_RecursoTipo", "RecursoTipo")]
        public RecursoTipo RecursoTipo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RecursoTipo>("BD_RESERVASModel.FK_Recurso_RecursoTipo", "RecursoTipo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RecursoTipo>("BD_RESERVASModel.FK_Recurso_RecursoTipo", "RecursoTipo").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RecursoTipo> RecursoTipoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RecursoTipo>("BD_RESERVASModel.FK_Recurso_RecursoTipo", "RecursoTipo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RecursoTipo>("BD_RESERVASModel.FK_Recurso_RecursoTipo", "RecursoTipo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_RESERVASModel", Name="RecursoTipo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RecursoTipo : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto RecursoTipo.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="sede">Valor inicial de la propiedad sede.</param>
        /// <param name="descripcion">Valor inicial de la propiedad descripcion.</param>
        /// <param name="tipoHora">Valor inicial de la propiedad tipoHora.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        public static RecursoTipo CreateRecursoTipo(global::System.Int32 id, global::System.Int32 sede, global::System.String descripcion, global::System.Int32 tipoHora, global::System.Boolean estado)
        {
            RecursoTipo recursoTipo = new RecursoTipo();
            recursoTipo.id = id;
            recursoTipo.sede = sede;
            recursoTipo.descripcion = descripcion;
            recursoTipo.tipoHora = tipoHora;
            recursoTipo.estado = estado;
            return recursoTipo;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sede
        {
            get
            {
                return _sede;
            }
            set
            {
                OnsedeChanging(value);
                ReportPropertyChanging("sede");
                _sede = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sede");
                OnsedeChanged();
            }
        }
        private global::System.Int32 _sede;
        partial void OnsedeChanging(global::System.Int32 value);
        partial void OnsedeChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tipoHora
        {
            get
            {
                return _tipoHora;
            }
            set
            {
                OntipoHoraChanging(value);
                ReportPropertyChanging("tipoHora");
                _tipoHora = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tipoHora");
                OntipoHoraChanged();
            }
        }
        private global::System.Int32 _tipoHora;
        partial void OntipoHoraChanging(global::System.Int32 value);
        partial void OntipoHoraChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Boolean _estado;
        partial void OnestadoChanging(global::System.Boolean value);
        partial void OnestadoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_RESERVASModel", "FK_Recurso_RecursoTipo", "Recurso")]
        public EntityCollection<Recurso> Recurso
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Recurso>("BD_RESERVASModel.FK_Recurso_RecursoTipo", "Recurso");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Recurso>("BD_RESERVASModel.FK_Recurso_RecursoTipo", "Recurso", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_RESERVASModel", "FK_RecursoTipoUsuarioTipo_RecursoTipo", "RecursoTipoHora")]
        public EntityCollection<RecursoTipoHora> RecursoTipoHora
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RecursoTipoHora>("BD_RESERVASModel.FK_RecursoTipoUsuarioTipo_RecursoTipo", "RecursoTipoHora");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RecursoTipoHora>("BD_RESERVASModel.FK_RecursoTipoUsuarioTipo_RecursoTipo", "RecursoTipoHora", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_RESERVASModel", "FK_RecursoTipo_HoraTipo", "HoraTipo")]
        public HoraTipo HoraTipo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HoraTipo>("BD_RESERVASModel.FK_RecursoTipo_HoraTipo", "HoraTipo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HoraTipo>("BD_RESERVASModel.FK_RecursoTipo_HoraTipo", "HoraTipo").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<HoraTipo> HoraTipoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HoraTipo>("BD_RESERVASModel.FK_RecursoTipo_HoraTipo", "HoraTipo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<HoraTipo>("BD_RESERVASModel.FK_RecursoTipo_HoraTipo", "HoraTipo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_RESERVASModel", Name="RecursoTipoHora")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RecursoTipoHora : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto RecursoTipoHora.
        /// </summary>
        /// <param name="recursoTipo">Valor inicial de la propiedad recursoTipo.</param>
        /// <param name="usuarioTipo">Valor inicial de la propiedad usuarioTipo.</param>
        public static RecursoTipoHora CreateRecursoTipoHora(global::System.Int32 recursoTipo, global::System.Int32 usuarioTipo)
        {
            RecursoTipoHora recursoTipoHora = new RecursoTipoHora();
            recursoTipoHora.recursoTipo = recursoTipo;
            recursoTipoHora.usuarioTipo = usuarioTipo;
            return recursoTipoHora;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 recursoTipo
        {
            get
            {
                return _recursoTipo;
            }
            set
            {
                if (_recursoTipo != value)
                {
                    OnrecursoTipoChanging(value);
                    ReportPropertyChanging("recursoTipo");
                    _recursoTipo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("recursoTipo");
                    OnrecursoTipoChanged();
                }
            }
        }
        private global::System.Int32 _recursoTipo;
        partial void OnrecursoTipoChanging(global::System.Int32 value);
        partial void OnrecursoTipoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 usuarioTipo
        {
            get
            {
                return _usuarioTipo;
            }
            set
            {
                if (_usuarioTipo != value)
                {
                    OnusuarioTipoChanging(value);
                    ReportPropertyChanging("usuarioTipo");
                    _usuarioTipo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("usuarioTipo");
                    OnusuarioTipoChanged();
                }
            }
        }
        private global::System.Int32 _usuarioTipo;
        partial void OnusuarioTipoChanging(global::System.Int32 value);
        partial void OnusuarioTipoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> nroHoras
        {
            get
            {
                return _nroHoras;
            }
            set
            {
                OnnroHorasChanging(value);
                ReportPropertyChanging("nroHoras");
                _nroHoras = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nroHoras");
                OnnroHorasChanged();
            }
        }
        private Nullable<global::System.Int32> _nroHoras;
        partial void OnnroHorasChanging(Nullable<global::System.Int32> value);
        partial void OnnroHorasChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_RESERVASModel", "FK_RecursoTipoUsuarioTipo_RecursoTipo", "RecursoTipo")]
        public RecursoTipo RecursoTipo1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RecursoTipo>("BD_RESERVASModel.FK_RecursoTipoUsuarioTipo_RecursoTipo", "RecursoTipo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RecursoTipo>("BD_RESERVASModel.FK_RecursoTipoUsuarioTipo_RecursoTipo", "RecursoTipo").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RecursoTipo> RecursoTipo1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RecursoTipo>("BD_RESERVASModel.FK_RecursoTipoUsuarioTipo_RecursoTipo", "RecursoTipo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RecursoTipo>("BD_RESERVASModel.FK_RecursoTipoUsuarioTipo_RecursoTipo", "RecursoTipo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_RESERVASModel", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Usuario.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="tipoUsuario">Valor inicial de la propiedad tipoUsuario.</param>
        /// <param name="codigo">Valor inicial de la propiedad codigo.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        public static Usuario CreateUsuario(global::System.Int32 id, global::System.Int32 tipoUsuario, global::System.String codigo, global::System.Boolean estado)
        {
            Usuario usuario = new Usuario();
            usuario.id = id;
            usuario.tipoUsuario = tipoUsuario;
            usuario.codigo = codigo;
            usuario.estado = estado;
            return usuario;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tipoUsuario
        {
            get
            {
                return _tipoUsuario;
            }
            set
            {
                OntipoUsuarioChanging(value);
                ReportPropertyChanging("tipoUsuario");
                _tipoUsuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tipoUsuario");
                OntipoUsuarioChanged();
            }
        }
        private global::System.Int32 _tipoUsuario;
        partial void OntipoUsuarioChanging(global::System.Int32 value);
        partial void OntipoUsuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                OncodigoChanging(value);
                ReportPropertyChanging("codigo");
                _codigo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("codigo");
                OncodigoChanged();
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Boolean _estado;
        partial void OnestadoChanging(global::System.Boolean value);
        partial void OnestadoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_RESERVASModel", "FK_Usuario_TipoUsuario", "UsuarioTipo")]
        public UsuarioTipo UsuarioTipo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsuarioTipo>("BD_RESERVASModel.FK_Usuario_TipoUsuario", "UsuarioTipo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsuarioTipo>("BD_RESERVASModel.FK_Usuario_TipoUsuario", "UsuarioTipo").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UsuarioTipo> UsuarioTipoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsuarioTipo>("BD_RESERVASModel.FK_Usuario_TipoUsuario", "UsuarioTipo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UsuarioTipo>("BD_RESERVASModel.FK_Usuario_TipoUsuario", "UsuarioTipo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_RESERVASModel", Name="UsuarioTipo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UsuarioTipo : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto UsuarioTipo.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        public static UsuarioTipo CreateUsuarioTipo(global::System.Int32 id, global::System.String nombre, global::System.Boolean estado)
        {
            UsuarioTipo usuarioTipo = new UsuarioTipo();
            usuarioTipo.id = id;
            usuarioTipo.nombre = nombre;
            usuarioTipo.estado = estado;
            return usuarioTipo;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Boolean _estado;
        partial void OnestadoChanging(global::System.Boolean value);
        partial void OnestadoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_RESERVASModel", "FK_Usuario_TipoUsuario", "Usuario")]
        public EntityCollection<Usuario> Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Usuario>("BD_RESERVASModel.FK_Usuario_TipoUsuario", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Usuario>("BD_RESERVASModel.FK_Usuario_TipoUsuario", "Usuario", value);
                }
            }
        }

        #endregion

    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="BD_RESERVASModel", Name="PA_SELECT_USUARIOS_X_CODIGO_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class PA_SELECT_USUARIOS_X_CODIGO_Result : ComplexObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto PA_SELECT_USUARIOS_X_CODIGO_Result.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="codigo">Valor inicial de la propiedad codigo.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        /// <param name="tipoUsuario">Valor inicial de la propiedad tipoUsuario.</param>
        /// <param name="nombreTipo">Valor inicial de la propiedad nombreTipo.</param>
        public static PA_SELECT_USUARIOS_X_CODIGO_Result CreatePA_SELECT_USUARIOS_X_CODIGO_Result(global::System.Int32 id, global::System.String codigo, global::System.Boolean estado, global::System.Int32 tipoUsuario, global::System.String nombreTipo)
        {
            PA_SELECT_USUARIOS_X_CODIGO_Result pA_SELECT_USUARIOS_X_CODIGO_Result = new PA_SELECT_USUARIOS_X_CODIGO_Result();
            pA_SELECT_USUARIOS_X_CODIGO_Result.id = id;
            pA_SELECT_USUARIOS_X_CODIGO_Result.codigo = codigo;
            pA_SELECT_USUARIOS_X_CODIGO_Result.estado = estado;
            pA_SELECT_USUARIOS_X_CODIGO_Result.tipoUsuario = tipoUsuario;
            pA_SELECT_USUARIOS_X_CODIGO_Result.nombreTipo = nombreTipo;
            return pA_SELECT_USUARIOS_X_CODIGO_Result;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                OnidChanging(value);
                ReportPropertyChanging("id");
                _id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id");
                OnidChanged();
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                OncodigoChanging(value);
                ReportPropertyChanging("codigo");
                _codigo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("codigo");
                OncodigoChanged();
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombreCompleto
        {
            get
            {
                return _nombreCompleto;
            }
            set
            {
                OnnombreCompletoChanging(value);
                ReportPropertyChanging("nombreCompleto");
                _nombreCompleto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombreCompleto");
                OnnombreCompletoChanged();
            }
        }
        private global::System.String _nombreCompleto;
        partial void OnnombreCompletoChanging(global::System.String value);
        partial void OnnombreCompletoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String codigoSede
        {
            get
            {
                return _codigoSede;
            }
            set
            {
                OncodigoSedeChanging(value);
                ReportPropertyChanging("codigoSede");
                _codigoSede = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("codigoSede");
                OncodigoSedeChanged();
            }
        }
        private global::System.String _codigoSede;
        partial void OncodigoSedeChanging(global::System.String value);
        partial void OncodigoSedeChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Boolean _estado;
        partial void OnestadoChanging(global::System.Boolean value);
        partial void OnestadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tipoUsuario
        {
            get
            {
                return _tipoUsuario;
            }
            set
            {
                OntipoUsuarioChanging(value);
                ReportPropertyChanging("tipoUsuario");
                _tipoUsuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tipoUsuario");
                OntipoUsuarioChanged();
            }
        }
        private global::System.Int32 _tipoUsuario;
        partial void OntipoUsuarioChanging(global::System.Int32 value);
        partial void OntipoUsuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombreTipo
        {
            get
            {
                return _nombreTipo;
            }
            set
            {
                OnnombreTipoChanging(value);
                ReportPropertyChanging("nombreTipo");
                _nombreTipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombreTipo");
                OnnombreTipoChanged();
            }
        }
        private global::System.String _nombreTipo;
        partial void OnnombreTipoChanging(global::System.String value);
        partial void OnnombreTipoChanged();

        #endregion

    }

    #endregion

    
}
