//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("BD_UPNSACModel", "FK_Aula_Sede", "Sede", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ReservasUPN.BE.Modelos.Sede), "Aula", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ReservasUPN.BE.Modelos.Aula), true)]

#endregion

namespace ReservasUPN.BE.Modelos
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class BD_UPNSACEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto BD_UPNSACEntities usando la cadena de conexión encontrada en la sección 'BD_UPNSACEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public BD_UPNSACEntities() : base("name=BD_UPNSACEntities", "BD_UPNSACEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BD_UPNSACEntities.
        /// </summary>
        public BD_UPNSACEntities(string connectionString) : base(connectionString, "BD_UPNSACEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BD_UPNSACEntities.
        /// </summary>
        public BD_UPNSACEntities(EntityConnection connection) : base(connection, "BD_UPNSACEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<AlumnosEgresados> AlumnosEgresados
        {
            get
            {
                if ((_AlumnosEgresados == null))
                {
                    _AlumnosEgresados = base.CreateObjectSet<AlumnosEgresados>("AlumnosEgresados");
                }
                return _AlumnosEgresados;
            }
        }
        private ObjectSet<AlumnosEgresados> _AlumnosEgresados;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<AlumnosRegulares> AlumnosRegulares
        {
            get
            {
                if ((_AlumnosRegulares == null))
                {
                    _AlumnosRegulares = base.CreateObjectSet<AlumnosRegulares>("AlumnosRegulares");
                }
                return _AlumnosRegulares;
            }
        }
        private ObjectSet<AlumnosRegulares> _AlumnosRegulares;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Sede> Sede
        {
            get
            {
                if ((_Sede == null))
                {
                    _Sede = base.CreateObjectSet<Sede>("Sede");
                }
                return _Sede;
            }
        }
        private ObjectSet<Sede> _Sede;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Aula> Aula
        {
            get
            {
                if ((_Aula == null))
                {
                    _Aula = base.CreateObjectSet<Aula>("Aula");
                }
                return _Aula;
            }
        }
        private ObjectSet<Aula> _Aula;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Hora> Hora
        {
            get
            {
                if ((_Hora == null))
                {
                    _Hora = base.CreateObjectSet<Hora>("Hora");
                }
                return _Hora;
            }
        }
        private ObjectSet<Hora> _Hora;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet AlumnosEgresados. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToAlumnosEgresados(AlumnosEgresados alumnosEgresados)
        {
            base.AddObject("AlumnosEgresados", alumnosEgresados);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet AlumnosRegulares. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToAlumnosRegulares(AlumnosRegulares alumnosRegulares)
        {
            base.AddObject("AlumnosRegulares", alumnosRegulares);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Sede. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToSede(Sede sede)
        {
            base.AddObject("Sede", sede);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Aula. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToAula(Aula aula)
        {
            base.AddObject("Aula", aula);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Hora. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToHora(Hora hora)
        {
            base.AddObject("Hora", hora);
        }

        #endregion

        #region Importaciones de funciones
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="p_CODIGO">No hay documentación de metadatos disponible.</param>
        public ObjectResult<PA_SELECT_DOCENTES_X_CODIGO_Result> PA_SELECT_DOCENTES_X_CODIGO(global::System.String p_CODIGO)
        {
            ObjectParameter p_CODIGOParameter;
            if (p_CODIGO != null)
            {
                p_CODIGOParameter = new ObjectParameter("P_CODIGO", p_CODIGO);
            }
            else
            {
                p_CODIGOParameter = new ObjectParameter("P_CODIGO", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<PA_SELECT_DOCENTES_X_CODIGO_Result>("PA_SELECT_DOCENTES_X_CODIGO", p_CODIGOParameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="p_AULA">No hay documentación de metadatos disponible.</param>
        public ObjectResult<PA_SELECT_HORARIO_X_AULA_Result> PA_SELECT_HORARIO_X_AULA(global::System.String p_AULA)
        {
            ObjectParameter p_AULAParameter;
            if (p_AULA != null)
            {
                p_AULAParameter = new ObjectParameter("P_AULA", p_AULA);
            }
            else
            {
                p_AULAParameter = new ObjectParameter("P_AULA", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<PA_SELECT_HORARIO_X_AULA_Result>("PA_SELECT_HORARIO_X_AULA", p_AULAParameter);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_UPNSACModel", Name="AlumnosEgresados")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AlumnosEgresados : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto AlumnosEgresados.
        /// </summary>
        /// <param name="codigo">Valor inicial de la propiedad codigo.</param>
        /// <param name="nombreCompleto">Valor inicial de la propiedad nombreCompleto.</param>
        /// <param name="sede">Valor inicial de la propiedad sede.</param>
        public static AlumnosEgresados CreateAlumnosEgresados(global::System.String codigo, global::System.String nombreCompleto, global::System.Int32 sede)
        {
            AlumnosEgresados alumnosEgresados = new AlumnosEgresados();
            alumnosEgresados.codigo = codigo;
            alumnosEgresados.nombreCompleto = nombreCompleto;
            alumnosEgresados.sede = sede;
            return alumnosEgresados;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                if (_codigo != value)
                {
                    OncodigoChanging(value);
                    ReportPropertyChanging("codigo");
                    _codigo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("codigo");
                    OncodigoChanged();
                }
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombreCompleto
        {
            get
            {
                return _nombreCompleto;
            }
            set
            {
                if (_nombreCompleto != value)
                {
                    OnnombreCompletoChanging(value);
                    ReportPropertyChanging("nombreCompleto");
                    _nombreCompleto = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("nombreCompleto");
                    OnnombreCompletoChanged();
                }
            }
        }
        private global::System.String _nombreCompleto;
        partial void OnnombreCompletoChanging(global::System.String value);
        partial void OnnombreCompletoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sede
        {
            get
            {
                return _sede;
            }
            set
            {
                if (_sede != value)
                {
                    OnsedeChanging(value);
                    ReportPropertyChanging("sede");
                    _sede = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("sede");
                    OnsedeChanged();
                }
            }
        }
        private global::System.Int32 _sede;
        partial void OnsedeChanging(global::System.Int32 value);
        partial void OnsedeChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sedeNombre
        {
            get
            {
                return _sedeNombre;
            }
            set
            {
                OnsedeNombreChanging(value);
                ReportPropertyChanging("sedeNombre");
                _sedeNombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sedeNombre");
                OnsedeNombreChanged();
            }
        }
        private global::System.String _sedeNombre;
        partial void OnsedeNombreChanging(global::System.String value);
        partial void OnsedeNombreChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_UPNSACModel", Name="AlumnosRegulares")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AlumnosRegulares : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto AlumnosRegulares.
        /// </summary>
        /// <param name="codigo">Valor inicial de la propiedad codigo.</param>
        /// <param name="nombreCompleto">Valor inicial de la propiedad nombreCompleto.</param>
        /// <param name="sede">Valor inicial de la propiedad sede.</param>
        public static AlumnosRegulares CreateAlumnosRegulares(global::System.String codigo, global::System.String nombreCompleto, global::System.Int32 sede)
        {
            AlumnosRegulares alumnosRegulares = new AlumnosRegulares();
            alumnosRegulares.codigo = codigo;
            alumnosRegulares.nombreCompleto = nombreCompleto;
            alumnosRegulares.sede = sede;
            return alumnosRegulares;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                if (_codigo != value)
                {
                    OncodigoChanging(value);
                    ReportPropertyChanging("codigo");
                    _codigo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("codigo");
                    OncodigoChanged();
                }
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombreCompleto
        {
            get
            {
                return _nombreCompleto;
            }
            set
            {
                if (_nombreCompleto != value)
                {
                    OnnombreCompletoChanging(value);
                    ReportPropertyChanging("nombreCompleto");
                    _nombreCompleto = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("nombreCompleto");
                    OnnombreCompletoChanged();
                }
            }
        }
        private global::System.String _nombreCompleto;
        partial void OnnombreCompletoChanging(global::System.String value);
        partial void OnnombreCompletoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sede
        {
            get
            {
                return _sede;
            }
            set
            {
                if (_sede != value)
                {
                    OnsedeChanging(value);
                    ReportPropertyChanging("sede");
                    _sede = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("sede");
                    OnsedeChanged();
                }
            }
        }
        private global::System.Int32 _sede;
        partial void OnsedeChanging(global::System.Int32 value);
        partial void OnsedeChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sedeNombre
        {
            get
            {
                return _sedeNombre;
            }
            set
            {
                OnsedeNombreChanging(value);
                ReportPropertyChanging("sedeNombre");
                _sedeNombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sedeNombre");
                OnsedeNombreChanged();
            }
        }
        private global::System.String _sedeNombre;
        partial void OnsedeNombreChanging(global::System.String value);
        partial void OnsedeNombreChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_UPNSACModel", Name="Aula")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Aula : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Aula.
        /// </summary>
        /// <param name="codigo">Valor inicial de la propiedad codigo.</param>
        /// <param name="sede">Valor inicial de la propiedad sede.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        public static Aula CreateAula(global::System.String codigo, global::System.Int32 sede, global::System.Boolean estado)
        {
            Aula aula = new Aula();
            aula.codigo = codigo;
            aula.sede = sede;
            aula.estado = estado;
            return aula;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                if (_codigo != value)
                {
                    OncodigoChanging(value);
                    ReportPropertyChanging("codigo");
                    _codigo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("codigo");
                    OncodigoChanged();
                }
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sede
        {
            get
            {
                return _sede;
            }
            set
            {
                if (_sede != value)
                {
                    OnsedeChanging(value);
                    ReportPropertyChanging("sede");
                    _sede = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("sede");
                    OnsedeChanged();
                }
            }
        }
        private global::System.Int32 _sede;
        partial void OnsedeChanging(global::System.Int32 value);
        partial void OnsedeChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Boolean _estado;
        partial void OnestadoChanging(global::System.Boolean value);
        partial void OnestadoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_UPNSACModel", "FK_Aula_Sede", "Sede")]
        public Sede Sede1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sede>("BD_UPNSACModel.FK_Aula_Sede", "Sede").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sede>("BD_UPNSACModel.FK_Aula_Sede", "Sede").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Sede> Sede1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sede>("BD_UPNSACModel.FK_Aula_Sede", "Sede");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Sede>("BD_UPNSACModel.FK_Aula_Sede", "Sede", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_UPNSACModel", Name="Hora")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Hora : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Hora.
        /// </summary>
        /// <param name="n_hora_id">Valor inicial de la propiedad n_hora_id.</param>
        /// <param name="n_hor_codigo">Valor inicial de la propiedad n_hor_codigo.</param>
        /// <param name="s_hor_descripcion">Valor inicial de la propiedad s_hor_descripcion.</param>
        /// <param name="d_hor_inicio">Valor inicial de la propiedad d_hor_inicio.</param>
        /// <param name="d_hor_final">Valor inicial de la propiedad d_hor_final.</param>
        /// <param name="n_hor_minutos">Valor inicial de la propiedad n_hor_minutos.</param>
        /// <param name="b_hor_activo">Valor inicial de la propiedad b_hor_activo.</param>
        public static Hora CreateHora(global::System.Int32 n_hora_id, global::System.Int32 n_hor_codigo, global::System.String s_hor_descripcion, global::System.TimeSpan d_hor_inicio, global::System.TimeSpan d_hor_final, global::System.Int32 n_hor_minutos, global::System.Boolean b_hor_activo)
        {
            Hora hora = new Hora();
            hora.n_hora_id = n_hora_id;
            hora.n_hor_codigo = n_hor_codigo;
            hora.s_hor_descripcion = s_hor_descripcion;
            hora.d_hor_inicio = d_hor_inicio;
            hora.d_hor_final = d_hor_final;
            hora.n_hor_minutos = n_hor_minutos;
            hora.b_hor_activo = b_hor_activo;
            return hora;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 n_hora_id
        {
            get
            {
                return _n_hora_id;
            }
            set
            {
                if (_n_hora_id != value)
                {
                    Onn_hora_idChanging(value);
                    ReportPropertyChanging("n_hora_id");
                    _n_hora_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("n_hora_id");
                    Onn_hora_idChanged();
                }
            }
        }
        private global::System.Int32 _n_hora_id;
        partial void Onn_hora_idChanging(global::System.Int32 value);
        partial void Onn_hora_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 n_hor_codigo
        {
            get
            {
                return _n_hor_codigo;
            }
            set
            {
                Onn_hor_codigoChanging(value);
                ReportPropertyChanging("n_hor_codigo");
                _n_hor_codigo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("n_hor_codigo");
                Onn_hor_codigoChanged();
            }
        }
        private global::System.Int32 _n_hor_codigo;
        partial void Onn_hor_codigoChanging(global::System.Int32 value);
        partial void Onn_hor_codigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String s_hor_descripcion
        {
            get
            {
                return _s_hor_descripcion;
            }
            set
            {
                Ons_hor_descripcionChanging(value);
                ReportPropertyChanging("s_hor_descripcion");
                _s_hor_descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("s_hor_descripcion");
                Ons_hor_descripcionChanged();
            }
        }
        private global::System.String _s_hor_descripcion;
        partial void Ons_hor_descripcionChanging(global::System.String value);
        partial void Ons_hor_descripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan d_hor_inicio
        {
            get
            {
                return _d_hor_inicio;
            }
            set
            {
                Ond_hor_inicioChanging(value);
                ReportPropertyChanging("d_hor_inicio");
                _d_hor_inicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("d_hor_inicio");
                Ond_hor_inicioChanged();
            }
        }
        private global::System.TimeSpan _d_hor_inicio;
        partial void Ond_hor_inicioChanging(global::System.TimeSpan value);
        partial void Ond_hor_inicioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan d_hor_final
        {
            get
            {
                return _d_hor_final;
            }
            set
            {
                Ond_hor_finalChanging(value);
                ReportPropertyChanging("d_hor_final");
                _d_hor_final = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("d_hor_final");
                Ond_hor_finalChanged();
            }
        }
        private global::System.TimeSpan _d_hor_final;
        partial void Ond_hor_finalChanging(global::System.TimeSpan value);
        partial void Ond_hor_finalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 n_hor_minutos
        {
            get
            {
                return _n_hor_minutos;
            }
            set
            {
                Onn_hor_minutosChanging(value);
                ReportPropertyChanging("n_hor_minutos");
                _n_hor_minutos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("n_hor_minutos");
                Onn_hor_minutosChanged();
            }
        }
        private global::System.Int32 _n_hor_minutos;
        partial void Onn_hor_minutosChanging(global::System.Int32 value);
        partial void Onn_hor_minutosChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean b_hor_activo
        {
            get
            {
                return _b_hor_activo;
            }
            set
            {
                Onb_hor_activoChanging(value);
                ReportPropertyChanging("b_hor_activo");
                _b_hor_activo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("b_hor_activo");
                Onb_hor_activoChanged();
            }
        }
        private global::System.Boolean _b_hor_activo;
        partial void Onb_hor_activoChanging(global::System.Boolean value);
        partial void Onb_hor_activoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String s_hor_tipo
        {
            get
            {
                return _s_hor_tipo;
            }
            set
            {
                Ons_hor_tipoChanging(value);
                ReportPropertyChanging("s_hor_tipo");
                _s_hor_tipo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("s_hor_tipo");
                Ons_hor_tipoChanged();
            }
        }
        private global::System.String _s_hor_tipo;
        partial void Ons_hor_tipoChanging(global::System.String value);
        partial void Ons_hor_tipoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_UPNSACModel", Name="Sede")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sede : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Sede.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        public static Sede CreateSede(global::System.Int32 id, global::System.String nombre, global::System.Boolean estado)
        {
            Sede sede = new Sede();
            sede.id = id;
            sede.nombre = nombre;
            sede.estado = estado;
            return sede;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Boolean _estado;
        partial void OnestadoChanging(global::System.Boolean value);
        partial void OnestadoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_UPNSACModel", "FK_Aula_Sede", "Aula")]
        public EntityCollection<Aula> Aula
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Aula>("BD_UPNSACModel.FK_Aula_Sede", "Aula");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Aula>("BD_UPNSACModel.FK_Aula_Sede", "Aula", value);
                }
            }
        }

        #endregion

    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="BD_UPNSACModel", Name="PA_SELECT_DOCENTES_X_CODIGO_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class PA_SELECT_DOCENTES_X_CODIGO_Result : ComplexObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto PA_SELECT_DOCENTES_X_CODIGO_Result.
        /// </summary>
        /// <param name="codigo">Valor inicial de la propiedad Codigo.</param>
        /// <param name="nombreCompleto">Valor inicial de la propiedad NombreCompleto.</param>
        /// <param name="sede">Valor inicial de la propiedad sede.</param>
        public static PA_SELECT_DOCENTES_X_CODIGO_Result CreatePA_SELECT_DOCENTES_X_CODIGO_Result(global::System.String codigo, global::System.String nombreCompleto, global::System.Int32 sede)
        {
            PA_SELECT_DOCENTES_X_CODIGO_Result pA_SELECT_DOCENTES_X_CODIGO_Result = new PA_SELECT_DOCENTES_X_CODIGO_Result();
            pA_SELECT_DOCENTES_X_CODIGO_Result.Codigo = codigo;
            pA_SELECT_DOCENTES_X_CODIGO_Result.NombreCompleto = nombreCompleto;
            pA_SELECT_DOCENTES_X_CODIGO_Result.sede = sede;
            return pA_SELECT_DOCENTES_X_CODIGO_Result;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Codigo
        {
            get
            {
                return _Codigo;
            }
            set
            {
                OnCodigoChanging(value);
                ReportPropertyChanging("Codigo");
                _Codigo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Codigo");
                OnCodigoChanged();
            }
        }
        private global::System.String _Codigo;
        partial void OnCodigoChanging(global::System.String value);
        partial void OnCodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreCompleto
        {
            get
            {
                return _NombreCompleto;
            }
            set
            {
                OnNombreCompletoChanging(value);
                ReportPropertyChanging("NombreCompleto");
                _NombreCompleto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombreCompleto");
                OnNombreCompletoChanged();
            }
        }
        private global::System.String _NombreCompleto;
        partial void OnNombreCompletoChanging(global::System.String value);
        partial void OnNombreCompletoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sede
        {
            get
            {
                return _sede;
            }
            set
            {
                OnsedeChanging(value);
                ReportPropertyChanging("sede");
                _sede = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sede");
                OnsedeChanged();
            }
        }
        private global::System.Int32 _sede;
        partial void OnsedeChanging(global::System.Int32 value);
        partial void OnsedeChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sedeNombre
        {
            get
            {
                return _sedeNombre;
            }
            set
            {
                OnsedeNombreChanging(value);
                ReportPropertyChanging("sedeNombre");
                _sedeNombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sedeNombre");
                OnsedeNombreChanged();
            }
        }
        private global::System.String _sedeNombre;
        partial void OnsedeNombreChanging(global::System.String value);
        partial void OnsedeNombreChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="BD_UPNSACModel", Name="PA_SELECT_HORARIO_X_AULA_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class PA_SELECT_HORARIO_X_AULA_Result : ComplexObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto PA_SELECT_HORARIO_X_AULA_Result.
        /// </summary>
        /// <param name="dIA">Valor inicial de la propiedad DIA.</param>
        /// <param name="n_HOR_CODIGO">Valor inicial de la propiedad N_HOR_CODIGO.</param>
        /// <param name="s_hor_descripcion">Valor inicial de la propiedad s_hor_descripcion.</param>
        /// <param name="d_hor_inicio">Valor inicial de la propiedad d_hor_inicio.</param>
        /// <param name="d_hor_final">Valor inicial de la propiedad d_hor_final.</param>
        public static PA_SELECT_HORARIO_X_AULA_Result CreatePA_SELECT_HORARIO_X_AULA_Result(global::System.Byte dIA, global::System.Int32 n_HOR_CODIGO, global::System.String s_hor_descripcion, global::System.TimeSpan d_hor_inicio, global::System.TimeSpan d_hor_final)
        {
            PA_SELECT_HORARIO_X_AULA_Result pA_SELECT_HORARIO_X_AULA_Result = new PA_SELECT_HORARIO_X_AULA_Result();
            pA_SELECT_HORARIO_X_AULA_Result.DIA = dIA;
            pA_SELECT_HORARIO_X_AULA_Result.N_HOR_CODIGO = n_HOR_CODIGO;
            pA_SELECT_HORARIO_X_AULA_Result.s_hor_descripcion = s_hor_descripcion;
            pA_SELECT_HORARIO_X_AULA_Result.d_hor_inicio = d_hor_inicio;
            pA_SELECT_HORARIO_X_AULA_Result.d_hor_final = d_hor_final;
            return pA_SELECT_HORARIO_X_AULA_Result;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte DIA
        {
            get
            {
                return _DIA;
            }
            set
            {
                OnDIAChanging(value);
                ReportPropertyChanging("DIA");
                _DIA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DIA");
                OnDIAChanged();
            }
        }
        private global::System.Byte _DIA;
        partial void OnDIAChanging(global::System.Byte value);
        partial void OnDIAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 N_HOR_CODIGO
        {
            get
            {
                return _N_HOR_CODIGO;
            }
            set
            {
                OnN_HOR_CODIGOChanging(value);
                ReportPropertyChanging("N_HOR_CODIGO");
                _N_HOR_CODIGO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("N_HOR_CODIGO");
                OnN_HOR_CODIGOChanged();
            }
        }
        private global::System.Int32 _N_HOR_CODIGO;
        partial void OnN_HOR_CODIGOChanging(global::System.Int32 value);
        partial void OnN_HOR_CODIGOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String s_hor_descripcion
        {
            get
            {
                return _s_hor_descripcion;
            }
            set
            {
                Ons_hor_descripcionChanging(value);
                ReportPropertyChanging("s_hor_descripcion");
                _s_hor_descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("s_hor_descripcion");
                Ons_hor_descripcionChanged();
            }
        }
        private global::System.String _s_hor_descripcion;
        partial void Ons_hor_descripcionChanging(global::System.String value);
        partial void Ons_hor_descripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan d_hor_inicio
        {
            get
            {
                return _d_hor_inicio;
            }
            set
            {
                Ond_hor_inicioChanging(value);
                ReportPropertyChanging("d_hor_inicio");
                _d_hor_inicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("d_hor_inicio");
                Ond_hor_inicioChanged();
            }
        }
        private global::System.TimeSpan _d_hor_inicio;
        partial void Ond_hor_inicioChanging(global::System.TimeSpan value);
        partial void Ond_hor_inicioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan d_hor_final
        {
            get
            {
                return _d_hor_final;
            }
            set
            {
                Ond_hor_finalChanging(value);
                ReportPropertyChanging("d_hor_final");
                _d_hor_final = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("d_hor_final");
                Ond_hor_finalChanged();
            }
        }
        private global::System.TimeSpan _d_hor_final;
        partial void Ond_hor_finalChanging(global::System.TimeSpan value);
        partial void Ond_hor_finalChanged();

        #endregion

    }

    #endregion

    
}
