//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ReservasUPN.BE
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class BD_RESERVASEntities1 : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto BD_RESERVASEntities1 usando la cadena de conexión encontrada en la sección 'BD_RESERVASEntities1' del archivo de configuración de la aplicación.
        /// </summary>
        public BD_RESERVASEntities1() : base("name=BD_RESERVASEntities1", "BD_RESERVASEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BD_RESERVASEntities1.
        /// </summary>
        public BD_RESERVASEntities1(string connectionString) : base(connectionString, "BD_RESERVASEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BD_RESERVASEntities1.
        /// </summary>
        public BD_RESERVASEntities1(EntityConnection connection) : base(connection, "BD_RESERVASEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Recursos> Recursos
        {
            get
            {
                if ((_Recursos == null))
                {
                    _Recursos = base.CreateObjectSet<Recursos>("Recursos");
                }
                return _Recursos;
            }
        }
        private ObjectSet<Recursos> _Recursos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TiposRecurso> TiposRecurso
        {
            get
            {
                if ((_TiposRecurso == null))
                {
                    _TiposRecurso = base.CreateObjectSet<TiposRecurso>("TiposRecurso");
                }
                return _TiposRecurso;
            }
        }
        private ObjectSet<TiposRecurso> _TiposRecurso;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Recursos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToRecursos(Recursos recursos)
        {
            base.AddObject("Recursos", recursos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TiposRecurso. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTiposRecurso(TiposRecurso tiposRecurso)
        {
            base.AddObject("TiposRecurso", tiposRecurso);
        }

        #endregion

        #region Importaciones de funciones
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="intSede">No hay documentación de metadatos disponible.</param>
        public ObjectResult<PA_GET_TIPO_RECURSOS_Result> PA_GET_TIPO_RECURSOS(Nullable<global::System.Int32> intSede)
        {
            ObjectParameter intSedeParameter;
            if (intSede.HasValue)
            {
                intSedeParameter = new ObjectParameter("intSede", intSede);
            }
            else
            {
                intSedeParameter = new ObjectParameter("intSede", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<PA_GET_TIPO_RECURSOS_Result>("PA_GET_TIPO_RECURSOS", intSedeParameter);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_RESERVASModel", Name="Recursos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Recursos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Recursos.
        /// </summary>
        /// <param name="idRecurso">Valor inicial de la propiedad idRecurso.</param>
        /// <param name="codigo">Valor inicial de la propiedad codigo.</param>
        /// <param name="descripcion">Valor inicial de la propiedad descripcion.</param>
        /// <param name="idTipoRecurso">Valor inicial de la propiedad idTipoRecurso.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        public static Recursos CreateRecursos(global::System.Int32 idRecurso, global::System.String codigo, global::System.String descripcion, global::System.Int32 idTipoRecurso, global::System.Int32 estado)
        {
            Recursos recursos = new Recursos();
            recursos.idRecurso = idRecurso;
            recursos.codigo = codigo;
            recursos.descripcion = descripcion;
            recursos.idTipoRecurso = idTipoRecurso;
            recursos.estado = estado;
            return recursos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idRecurso
        {
            get
            {
                return _idRecurso;
            }
            set
            {
                if (_idRecurso != value)
                {
                    OnidRecursoChanging(value);
                    ReportPropertyChanging("idRecurso");
                    _idRecurso = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idRecurso");
                    OnidRecursoChanged();
                }
            }
        }
        private global::System.Int32 _idRecurso;
        partial void OnidRecursoChanging(global::System.Int32 value);
        partial void OnidRecursoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                OncodigoChanging(value);
                ReportPropertyChanging("codigo");
                _codigo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("codigo");
                OncodigoChanged();
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idTipoRecurso
        {
            get
            {
                return _idTipoRecurso;
            }
            set
            {
                OnidTipoRecursoChanging(value);
                ReportPropertyChanging("idTipoRecurso");
                _idTipoRecurso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idTipoRecurso");
                OnidTipoRecursoChanged();
            }
        }
        private global::System.Int32 _idTipoRecurso;
        partial void OnidTipoRecursoChanging(global::System.Int32 value);
        partial void OnidTipoRecursoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Int32 _estado;
        partial void OnestadoChanging(global::System.Int32 value);
        partial void OnestadoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_RESERVASModel", Name="TiposRecurso")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TiposRecurso : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TiposRecurso.
        /// </summary>
        /// <param name="idTipoRecurso">Valor inicial de la propiedad idTipoRecurso.</param>
        /// <param name="idSede">Valor inicial de la propiedad idSede.</param>
        /// <param name="descripcion">Valor inicial de la propiedad descripcion.</param>
        /// <param name="idTipoHora">Valor inicial de la propiedad idTipoHora.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        public static TiposRecurso CreateTiposRecurso(global::System.Int32 idTipoRecurso, global::System.Int32 idSede, global::System.String descripcion, global::System.Int32 idTipoHora, global::System.Int32 estado)
        {
            TiposRecurso tiposRecurso = new TiposRecurso();
            tiposRecurso.idTipoRecurso = idTipoRecurso;
            tiposRecurso.idSede = idSede;
            tiposRecurso.descripcion = descripcion;
            tiposRecurso.idTipoHora = idTipoHora;
            tiposRecurso.estado = estado;
            return tiposRecurso;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idTipoRecurso
        {
            get
            {
                return _idTipoRecurso;
            }
            set
            {
                if (_idTipoRecurso != value)
                {
                    OnidTipoRecursoChanging(value);
                    ReportPropertyChanging("idTipoRecurso");
                    _idTipoRecurso = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idTipoRecurso");
                    OnidTipoRecursoChanged();
                }
            }
        }
        private global::System.Int32 _idTipoRecurso;
        partial void OnidTipoRecursoChanging(global::System.Int32 value);
        partial void OnidTipoRecursoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idSede
        {
            get
            {
                return _idSede;
            }
            set
            {
                OnidSedeChanging(value);
                ReportPropertyChanging("idSede");
                _idSede = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idSede");
                OnidSedeChanged();
            }
        }
        private global::System.Int32 _idSede;
        partial void OnidSedeChanging(global::System.Int32 value);
        partial void OnidSedeChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idTipoHora
        {
            get
            {
                return _idTipoHora;
            }
            set
            {
                OnidTipoHoraChanging(value);
                ReportPropertyChanging("idTipoHora");
                _idTipoHora = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idTipoHora");
                OnidTipoHoraChanged();
            }
        }
        private global::System.Int32 _idTipoHora;
        partial void OnidTipoHoraChanging(global::System.Int32 value);
        partial void OnidTipoHoraChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Int32 _estado;
        partial void OnestadoChanging(global::System.Int32 value);
        partial void OnestadoChanged();

        #endregion

    
    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="BD_RESERVASModel", Name="PA_GET_TIPO_RECURSOS_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class PA_GET_TIPO_RECURSOS_Result : ComplexObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto PA_GET_TIPO_RECURSOS_Result.
        /// </summary>
        /// <param name="idTipoRecurso">Valor inicial de la propiedad idTipoRecurso.</param>
        /// <param name="idSede">Valor inicial de la propiedad idSede.</param>
        /// <param name="descripcion">Valor inicial de la propiedad descripcion.</param>
        /// <param name="idTipoHora">Valor inicial de la propiedad idTipoHora.</param>
        public static PA_GET_TIPO_RECURSOS_Result CreatePA_GET_TIPO_RECURSOS_Result(global::System.Int32 idTipoRecurso, global::System.Int32 idSede, global::System.String descripcion, global::System.Int32 idTipoHora)
        {
            PA_GET_TIPO_RECURSOS_Result pA_GET_TIPO_RECURSOS_Result = new PA_GET_TIPO_RECURSOS_Result();
            pA_GET_TIPO_RECURSOS_Result.idTipoRecurso = idTipoRecurso;
            pA_GET_TIPO_RECURSOS_Result.idSede = idSede;
            pA_GET_TIPO_RECURSOS_Result.descripcion = descripcion;
            pA_GET_TIPO_RECURSOS_Result.idTipoHora = idTipoHora;
            return pA_GET_TIPO_RECURSOS_Result;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idTipoRecurso
        {
            get
            {
                return _idTipoRecurso;
            }
            set
            {
                OnidTipoRecursoChanging(value);
                ReportPropertyChanging("idTipoRecurso");
                _idTipoRecurso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idTipoRecurso");
                OnidTipoRecursoChanged();
            }
        }
        private global::System.Int32 _idTipoRecurso;
        partial void OnidTipoRecursoChanging(global::System.Int32 value);
        partial void OnidTipoRecursoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idSede
        {
            get
            {
                return _idSede;
            }
            set
            {
                OnidSedeChanging(value);
                ReportPropertyChanging("idSede");
                _idSede = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idSede");
                OnidSedeChanged();
            }
        }
        private global::System.Int32 _idSede;
        partial void OnidSedeChanging(global::System.Int32 value);
        partial void OnidSedeChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idTipoHora
        {
            get
            {
                return _idTipoHora;
            }
            set
            {
                OnidTipoHoraChanging(value);
                ReportPropertyChanging("idTipoHora");
                _idTipoHora = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idTipoHora");
                OnidTipoHoraChanged();
            }
        }
        private global::System.Int32 _idTipoHora;
        partial void OnidTipoHoraChanging(global::System.Int32 value);
        partial void OnidTipoHoraChanged();

        #endregion

    }

    #endregion

    
}
