//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ReservasUPN.BE
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class BD_UPNSACEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto BD_UPNSACEntities usando la cadena de conexión encontrada en la sección 'BD_UPNSACEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public BD_UPNSACEntities() : base("name=BD_UPNSACEntities", "BD_UPNSACEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BD_UPNSACEntities.
        /// </summary>
        public BD_UPNSACEntities(string connectionString) : base(connectionString, "BD_UPNSACEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BD_UPNSACEntities.
        /// </summary>
        public BD_UPNSACEntities(EntityConnection connection) : base(connection, "BD_UPNSACEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Alumno> Alumnoes
        {
            get
            {
                if ((_Alumnoes == null))
                {
                    _Alumnoes = base.CreateObjectSet<Alumno>("Alumnoes");
                }
                return _Alumnoes;
            }
        }
        private ObjectSet<Alumno> _Alumnoes;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Carrera> Carreras
        {
            get
            {
                if ((_Carreras == null))
                {
                    _Carreras = base.CreateObjectSet<Carrera>("Carreras");
                }
                return _Carreras;
            }
        }
        private ObjectSet<Carrera> _Carreras;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Sucursal> Sucursals
        {
            get
            {
                if ((_Sucursals == null))
                {
                    _Sucursals = base.CreateObjectSet<Sucursal>("Sucursals");
                }
                return _Sucursals;
            }
        }
        private ObjectSet<Sucursal> _Sucursals;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TipoHora> TipoHoras
        {
            get
            {
                if ((_TipoHoras == null))
                {
                    _TipoHoras = base.CreateObjectSet<TipoHora>("TipoHoras");
                }
                return _TipoHoras;
            }
        }
        private ObjectSet<TipoHora> _TipoHoras;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Alumnoes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToAlumnoes(Alumno alumno)
        {
            base.AddObject("Alumnoes", alumno);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Carreras. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCarreras(Carrera carrera)
        {
            base.AddObject("Carreras", carrera);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Sucursals. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToSucursals(Sucursal sucursal)
        {
            base.AddObject("Sucursals", sucursal);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TipoHoras. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTipoHoras(TipoHora tipoHora)
        {
            base.AddObject("TipoHoras", tipoHora);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_UPNSACModel", Name="Alumno")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Alumno : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Alumno.
        /// </summary>
        /// <param name="codigo">Valor inicial de la propiedad codigo.</param>
        public static Alumno CreateAlumno(global::System.String codigo)
        {
            Alumno alumno = new Alumno();
            alumno.codigo = codigo;
            return alumno;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                if (_codigo != value)
                {
                    OncodigoChanging(value);
                    ReportPropertyChanging("codigo");
                    _codigo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("codigo");
                    OncodigoChanged();
                }
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ApellidoPaterno
        {
            get
            {
                return _ApellidoPaterno;
            }
            set
            {
                OnApellidoPaternoChanging(value);
                ReportPropertyChanging("ApellidoPaterno");
                _ApellidoPaterno = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ApellidoPaterno");
                OnApellidoPaternoChanged();
            }
        }
        private global::System.String _ApellidoPaterno;
        partial void OnApellidoPaternoChanging(global::System.String value);
        partial void OnApellidoPaternoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ApellidoMaterno
        {
            get
            {
                return _ApellidoMaterno;
            }
            set
            {
                OnApellidoMaternoChanging(value);
                ReportPropertyChanging("ApellidoMaterno");
                _ApellidoMaterno = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ApellidoMaterno");
                OnApellidoMaternoChanged();
            }
        }
        private global::System.String _ApellidoMaterno;
        partial void OnApellidoMaternoChanging(global::System.String value);
        partial void OnApellidoMaternoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_UPNSACModel", Name="Carrera")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Carrera : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Carrera.
        /// </summary>
        /// <param name="codCarrera">Valor inicial de la propiedad CodCarrera.</param>
        public static Carrera CreateCarrera(global::System.Int32 codCarrera)
        {
            Carrera carrera = new Carrera();
            carrera.CodCarrera = codCarrera;
            return carrera;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CodCarrera
        {
            get
            {
                return _CodCarrera;
            }
            set
            {
                if (_CodCarrera != value)
                {
                    OnCodCarreraChanging(value);
                    ReportPropertyChanging("CodCarrera");
                    _CodCarrera = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CodCarrera");
                    OnCodCarreraChanged();
                }
            }
        }
        private global::System.Int32 _CodCarrera;
        partial void OnCodCarreraChanging(global::System.Int32 value);
        partial void OnCodCarreraChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DescripcionCorta
        {
            get
            {
                return _DescripcionCorta;
            }
            set
            {
                OnDescripcionCortaChanging(value);
                ReportPropertyChanging("DescripcionCorta");
                _DescripcionCorta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DescripcionCorta");
                OnDescripcionCortaChanged();
            }
        }
        private global::System.String _DescripcionCorta;
        partial void OnDescripcionCortaChanging(global::System.String value);
        partial void OnDescripcionCortaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Cod_Sucursal
        {
            get
            {
                return _Cod_Sucursal;
            }
            set
            {
                OnCod_SucursalChanging(value);
                ReportPropertyChanging("Cod_Sucursal");
                _Cod_Sucursal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cod_Sucursal");
                OnCod_SucursalChanged();
            }
        }
        private Nullable<global::System.Int32> _Cod_Sucursal;
        partial void OnCod_SucursalChanging(Nullable<global::System.Int32> value);
        partial void OnCod_SucursalChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_UPNSACModel", Name="Sucursal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sucursal : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Sucursal.
        /// </summary>
        /// <param name="cod_Sucursal">Valor inicial de la propiedad Cod_Sucursal.</param>
        public static Sucursal CreateSucursal(global::System.Int32 cod_Sucursal)
        {
            Sucursal sucursal = new Sucursal();
            sucursal.Cod_Sucursal = cod_Sucursal;
            return sucursal;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cod_Sucursal
        {
            get
            {
                return _Cod_Sucursal;
            }
            set
            {
                if (_Cod_Sucursal != value)
                {
                    OnCod_SucursalChanging(value);
                    ReportPropertyChanging("Cod_Sucursal");
                    _Cod_Sucursal = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Cod_Sucursal");
                    OnCod_SucursalChanged();
                }
            }
        }
        private global::System.Int32 _Cod_Sucursal;
        partial void OnCod_SucursalChanging(global::System.Int32 value);
        partial void OnCod_SucursalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Lugar
        {
            get
            {
                return _Lugar;
            }
            set
            {
                OnLugarChanging(value);
                ReportPropertyChanging("Lugar");
                _Lugar = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Lugar");
                OnLugarChanged();
            }
        }
        private global::System.String _Lugar;
        partial void OnLugarChanging(global::System.String value);
        partial void OnLugarChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DescripcionCorta
        {
            get
            {
                return _DescripcionCorta;
            }
            set
            {
                OnDescripcionCortaChanging(value);
                ReportPropertyChanging("DescripcionCorta");
                _DescripcionCorta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DescripcionCorta");
                OnDescripcionCortaChanged();
            }
        }
        private global::System.String _DescripcionCorta;
        partial void OnDescripcionCortaChanging(global::System.String value);
        partial void OnDescripcionCortaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_UPNSACModel", Name="TipoHora")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TipoHora : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TipoHora.
        /// </summary>
        /// <param name="idTiposHora">Valor inicial de la propiedad idTiposHora.</param>
        /// <param name="descripcion">Valor inicial de la propiedad descripcion.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        public static TipoHora CreateTipoHora(global::System.Int32 idTiposHora, global::System.String descripcion, global::System.Int32 estado)
        {
            TipoHora tipoHora = new TipoHora();
            tipoHora.idTiposHora = idTiposHora;
            tipoHora.descripcion = descripcion;
            tipoHora.estado = estado;
            return tipoHora;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idTiposHora
        {
            get
            {
                return _idTiposHora;
            }
            set
            {
                if (_idTiposHora != value)
                {
                    OnidTiposHoraChanging(value);
                    ReportPropertyChanging("idTiposHora");
                    _idTiposHora = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idTiposHora");
                    OnidTiposHoraChanged();
                }
            }
        }
        private global::System.Int32 _idTiposHora;
        partial void OnidTiposHoraChanging(global::System.Int32 value);
        partial void OnidTiposHoraChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Int32 _estado;
        partial void OnestadoChanging(global::System.Int32 value);
        partial void OnestadoChanged();

        #endregion

    
    }

    #endregion

    
}
